[package]
name = "zaptome-fuentes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
reqwest = { version = "0.13.3", features = ["json", "query"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.151"
zaptome-dominio = { path = "../dominio" }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
